"""login y pagos por jornada

Revision ID: 56a0b4cf0c8e
Revises: fa542e9323b1
Create Date: 2026-04-05 17:37:48.844491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a0b4cf0c8e'
down_revision = 'fa542e9323b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos_jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jornada_grupo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.Column('confirmado_por_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jornada_grupo_id'], ['jornadas_grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'jornada_grupo_id', name='uq_pago_usuario_jornada')
    )
    with op.batch_alter_table('pagos_jornada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_jornada_jornada_grupo_id'), ['jornada_grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_jornada_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('pagos_jornada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_jornada_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_jornada_jornada_grupo_id'))

    op.drop_table('pagos_jornada')
    # ### end Alembic commands ###
