"""modelos iniciales

Revision ID: fa542e9323b1
Revises: 
Create Date: 2026-04-05 16:34:35.777906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa542e9323b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_nombre'), ['nombre'], unique=True)

    op.create_table('pozos_acumulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('monto_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('es_sudamericano', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_nombre'), ['nombre'], unique=True)

    op.create_table('jornadas_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('numero_jornada', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('valor_apuesta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_premio_jornada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_acumulado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_utilidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'numero_jornada', name='uq_grupo_jornada')
    )
    with op.batch_alter_table('jornadas_grupo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jornadas_grupo_grupo_id'), ['grupo_id'], unique=False)

    op.create_table('usuarios_acumulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jornadas_validas_acumuladas', sa.Integer(), nullable=False),
    sa.Column('monto_acumulado_aportado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('habilitado_gran_final', sa.Boolean(), nullable=False),
    sa.Column('fecha_habilitacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios_acumulado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_acumulado_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('apuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jornada_grupo_id', sa.Integer(), nullable=False),
    sa.Column('valor_apostado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_premio_jornada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_aporte_acumulado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_utilidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('puntos_total', sa.Integer(), nullable=False),
    sa.Column('exactos', sa.Integer(), nullable=False),
    sa.Column('aciertos_resultado', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.Column('es_valida_para_acumulado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_grupo_id'], ['jornadas_grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'jornada_grupo_id', name='uq_usuario_jornada_apuesta')
    )
    with op.batch_alter_table('apuestas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apuestas_jornada_grupo_id'), ['jornada_grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apuestas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_grupo_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('numero_calendario', sa.Integer(), nullable=True),
    sa.Column('fecha_partido', sa.Date(), nullable=False),
    sa.Column('hora_est', sa.String(length=10), nullable=True),
    sa.Column('hora_local', sa.String(length=10), nullable=True),
    sa.Column('equipo_local_id', sa.Integer(), nullable=False),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=False),
    sa.Column('estadio', sa.String(length=150), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['jornada_grupo_id'], ['jornadas_grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidos_equipo_local_id'), ['equipo_local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_equipo_visitante_id'), ['equipo_visitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_jornada_grupo_id'), ['jornada_grupo_id'], unique=False)

    op.create_table('movimientos_acumulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pozo_acumulado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('apuesta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apuesta_id'], ['apuestas.id'], ),
    sa.ForeignKeyConstraint(['pozo_acumulado_id'], ['pozos_acumulado.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_acumulado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_acumulado_apuesta_id'), ['apuesta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_acumulado_pozo_acumulado_id'), ['pozo_acumulado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_acumulado_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apuesta_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('goles_local_pred', sa.Integer(), nullable=False),
    sa.Column('goles_visitante_pred', sa.Integer(), nullable=False),
    sa.Column('puntos_obtenidos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apuesta_id'], ['apuestas.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apuesta_id', 'partido_id', name='uq_apuesta_partido')
    )
    with op.batch_alter_table('pronosticos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronosticos_apuesta_id'), ['apuesta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pronosticos_partido_id'), ['partido_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pronosticos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronosticos_partido_id'))
        batch_op.drop_index(batch_op.f('ix_pronosticos_apuesta_id'))

    op.drop_table('pronosticos')
    with op.batch_alter_table('movimientos_acumulado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_acumulado_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_acumulado_pozo_acumulado_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_acumulado_apuesta_id'))

    op.drop_table('movimientos_acumulado')
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidos_jornada_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_partidos_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_partidos_equipo_visitante_id'))
        batch_op.drop_index(batch_op.f('ix_partidos_equipo_local_id'))

    op.drop_table('partidos')
    with op.batch_alter_table('apuestas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apuestas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_apuestas_jornada_grupo_id'))

    op.drop_table('apuestas')
    with op.batch_alter_table('usuarios_acumulado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_acumulado_usuario_id'))

    op.drop_table('usuarios_acumulado')
    with op.batch_alter_table('jornadas_grupo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jornadas_grupo_grupo_id'))

    op.drop_table('jornadas_grupo')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_nombre'))
        batch_op.drop_index(batch_op.f('ix_equipos_grupo_id'))

    op.drop_table('equipos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('pozos_acumulado')
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_nombre'))

    op.drop_table('grupos')
    # ### end Alembic commands ###
